version: '3.0'

services:

  front-service:
    build: netology-diplom-frontend/
    container_name: front_container
    command: npm run serve
    ports:
      - "8081:8080"
    depends_on:
      - spring-service
    networks:
      - network_front_spring

  spring-service:
    build:
      context: ./
    container_name: spring_container
    volumes:
      - C:/Diploma/Downloads:/var/lib/cloud
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
    networks:
      - network_front_spring
      - network_spring_mysql

  mysql-service:
    image: mysql:latest
    container_name: mysql_container
    volumes:
      - C:/Diploma/DataBase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    networks:
      - network_spring_mysql

networks:
  network_front_spring:
  network_spring_mysql:
