-- insert into my_users(login, password, first_name, last_name, role)
-- values('user', 'password', 'Katya', 'Ivanova', 'USER');
--
-- insert into my_users(login, password, first_name, last_name, role)
-- values('admin', 'password', 'Vasiliy', 'Pupkin', 'ADMIN');